// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/team[teamIndex].tsx";
import * as $$0 from "./islands/home.tsx";
import * as $$1 from "./islands/something.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/team[teamIndex].tsx": $1,
  },
  islands: {
    "./islands/home.tsx": $$0,
    "./islands/something.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
